# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Mixer' do
  use_frameworks!
  pod 'React', :path => '../js/node_modules/react-native', :subspecs => [
    'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    'RCTAnimation',
    'DevSupport',
  ]
  pod "Yoga", :path => "../js/node_modules/react-native/ReactCommon/yoga"
end
